version: '3'
services:
  redis:
    container_name: ehredis
    image: redis
    ports: 
      - "6379:6379"
  db:
    container_name: ehmaria
    image: mariadb:10.2.21 ## 10.2.22, 10.2.22-bionic, 10.3.13, 10.4.3
    ports: 
      - "3306:3306"
    volumes:
      - /d/git/playNode/maria/conf:/etc/mysql/conf.d
      - /d/git/playNode/maria/data:/var/lib/mysql
      - /d/git/playNode/maria/init:/etc/mysql/init
    environment: 
      MYSQL_ROOT_PASSWORD: "!Qa109"
      MYSQL_USER: "ehrms2_user"
      MYSQL_PASSWORD: "104104"
    command:
      "mysqld --innodb-flush-method=fsync"
      # "/docker-entrypoint-initdb.d/init.sh" 
      # not necersary