version: '3'
services:
  redis:
    container_name: ehredis
    image: redis
    ports: 
    - "6379:6379"
  db:
    container_name: ehmaria
    image: mariadb:10.2.21
    ports: 
    - "3306:3306"
    volumes:
    - "./mysqlPath:/var/lib/mysql"
    environment: 
      MYSQL_ROOT_PASSWORD: "!Qa109"
      MYSQL_DATABASE: "ehrms2"
      MYdSQL_USER: "ehrms2_user"
      MYSQL_USER: "104104"
    command:
      "mysqld --innodb-flush-method=fsync"