version: '3'
services:
  redis:
    container_name: ehredis
    image: redis
    ports: 
    - "6379:6379"
  db:
    container_name: ehmaria
    image: mariadb
    ports: 
    - "3306:3306"
    volumes:
    - myDB:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: "!Qa109"
volumes:
  myDB: 